version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/ethos-multi
    overwrite: true
permissions:
  - object: /var/www/html/ethos-multi
    pattern: '**'
    owner: www-data
    group: www-data
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationDeploy:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
